_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/faster_rcnn/faster_rcnn_R_50_FPN_ft_novel_30shot/model_reset_combine.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_BOX_HEAD:
    DROPOUT: 0.5
  ROI_HEADS:
    NUM_CLASSES: 80
    OUTPUT_LAYER: "CosineSimOutputLayers"
  BACKBONE:
    FREEZE: True
DATASETS:
  TRAIN: ('coco_trainval_all_30shot',)
  FS_TRAIN: ('coco_trainval_all_30shot',)
  TEST: ('coco_test_all',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (132000,)
  MAX_ITER: 132000 
  CHECKPOINT_PERIOD: 12000
  WARMUP_ITERS: 10
OUTPUT_DIR: "checkpoints/coco/faster_rcnn/faster_rcnn_R_50_FPN_ft_all_30shot_aug_ftmore_dropout"
INPUT:
  COLOR_JITTER: True
  MOSAIC: 0.5
  MOSAIC49SPLIT: 1.0
  CROP:
    ENABLED: True
    SIZE: [0.7,0.7]
